# frozen_string_literal: true

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: helloworld.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file('helloworld.proto', syntax: :proto3) do
    add_message 'HelloRequest' do
      optional :name, :string, 1
    end
    add_message 'HelloReply' do
      optional :message, :string, 1
    end
  end
end

module Nonnative
  module Features
    HelloRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup('HelloRequest').msgclass
    HelloReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup('HelloReply').msgclass
  end
end
