# frozen_string_literal: true

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: helloworld.proto for package 'Nonnative.Features'

require 'grpc'
require_relative 'helloworld_pb'

module Nonnative
  module Features
    module Greeter
      # The greeting service definition.
      class Service
        include GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'Greeter'

        # Sends a greeting
        rpc :SayHello, Nonnative::Features::HelloRequest, Nonnative::Features::HelloReply
      end

      Stub = Service.rpc_stub_class
    end
  end
end
