AllCops:
  TargetRubyVersion: 2.7
  DisplayCopNames: true
  NewCops: enable

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

Metrics/BlockLength:
  Max: 80

Metrics/AbcSize:
  Max: 20

Style/Documentation:
  Enabled: false
