AllCops:
  TargetRubyVersion: 3.2
  DisplayCopNames: true
  NewCops: enable

Layout/LineLength:
  Max: 165

Metrics/MethodLength:
  Max: 20

Metrics/BlockLength:
  Max: 80

Metrics/AbcSize:
  Max: 22

Style/Documentation:
  Enabled: false

Lint/HashCompareByIdentity:
  Enabled: false
