AllCops:
  TargetRubyVersion: 2.6
  DisplayCopNames: true

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 15

Style/Documentation:
  Enabled: false

Lint/RaiseException:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true
