AllCops:
  TargetRubyVersion: 3.2
  DisplayCopNames: true
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'

Layout/LineLength:
  Max: 150

Metrics/MethodLength:
  Max: 20

Metrics/BlockLength:
  Max: 85

Metrics/AbcSize:
  Max: 22

Style/Documentation:
  Enabled: false

Lint/HashCompareByIdentity:
  Enabled: false
