AllCops:
  TargetRubyVersion: 3.3
  DisplayCopNames: true
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'test/grpc/**/*'

Layout/LineLength:
  Max: 150

Metrics/MethodLength:
  Max: 20

Metrics/BlockLength:
  Max: 80

Metrics/AbcSize:
  Max: 22

Style/Documentation:
  Enabled: false

Lint/HashCompareByIdentity:
  Enabled: false
