# frozen_string_literal: true

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nonnative/v1/greeter.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file('nonnative/v1/greeter.proto', syntax: :proto3) do
    add_message 'nonnative.v1.SayHelloRequest' do
      optional :name, :string, 1, json_name: 'name'
    end
    add_message 'nonnative.v1.SayHelloResponse' do
      optional :message, :string, 1, json_name: 'message'
    end
  end
end

module Nonnative
  module Features
    SayHelloRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup('nonnative.v1.SayHelloRequest').msgclass
    SayHelloResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup('nonnative.v1.SayHelloResponse').msgclass
  end
end
