version: 2.1

jobs:
  build:
    docker:
      - image: alexfalkowski/ruby:2.4
    working_directory: ~/nonnative
    steps:
      - checkout:
          method: blobless
      - run: git submodule sync
      - run: git submodule update --init
      - run: make source-key
      - restore_cache:
          name: restore deps
          keys:
            - nonnative-ruby-cache-{{ checksum "Gemfile.lock" }}-{{ checksum "~/.ruby-version" }}-{{ checksum ".source-key" }}
            - nonnative-ruby-cache-
      - run: make dep
      - run: make clean-dep
      - save_cache:
          name: save deps
          key: nonnative-ruby-cache-{{ checksum "Gemfile.lock" }}-{{ checksum "~/.ruby-version" }}-{{ checksum ".source-key" }}
          paths:
            - vendor
      - run: make lint
      - run: make sec
      - run: COVERAGE_NAME="Cucumber Features" make features
      - run: COVERAGE_NAME="Cucumber Benchmarks" make benchmarks
      - store_test_results:
          path: test/reports
      - store_artifacts:
          path: test/reports
      - run: make codecov-upload
    resource_class: arm.large
  sync:
    docker:
      - image: alexfalkowski/release:7.5
    working_directory: ~/nonnative
    steps:
      - checkout:
          method: blobless
      - run: git submodule sync
      - run: git submodule update --init
      - run: make sync push
    resource_class: arm.large
  version:
    docker:
      - image: alexfalkowski/release:7.5
    working_directory: ~/nonnative
    steps:
      - checkout:
          method: blobless
      - run: git submodule sync
      - run: git submodule update --init
      - run: version
      - run: package
    resource_class: arm.large
  wait-all:
    docker:
      - image: alexfalkowski/ruby:2.4
    steps:
      - run: echo "all applicable jobs finished"
    resource_class: arm.large

workflows:
  nonnative:
    jobs:
      - build
      - sync:
          requires:
            - build
          filters:
            branches:
              ignore: master
      - version:
          context: gh
          serial-group: << pipeline.project.slug >>/version
          requires:
            - build
          filters:
            branches:
              only: master
      - wait-all:
          requires:
            - build
            - sync
            - version
