version: 2.1

commands:
  sync-submodules:
    steps:
      - run: git submodule sync
      - run: git submodule update --init
  checkout-submodules:
    steps:
      - checkout:
          method: blobless
      - sync-submodules

executors:
  ruby:
    docker:
      - image: alexfalkowski/ruby:3.24
  release:
    docker:
      - image: alexfalkowski/release:8.26
  alpine:
    docker:
      - image: alpine:latest

jobs:
  build:
    executor: ruby
    working_directory: ~/nonnative
    steps:
      - checkout-submodules
      - run: make source-key
      - restore_cache:
          name: restore deps
          keys:
            - nonnative-ruby-cache-{{ checksum "Gemfile.lock" }}-{{ checksum "~/.ruby-version" }}
            - nonnative-ruby-cache-
      - run: make dep
      - run: make clean-dep
      - save_cache:
          name: save deps
          key: nonnative-ruby-cache-{{ checksum "Gemfile.lock" }}-{{ checksum "~/.ruby-version" }}
          paths:
            - vendor
      - run: make lint
      - run: make sec
      - run: make features
      - run: make benchmarks
      - store_test_results:
          path: test/reports
      - store_artifacts:
          path: test/reports
      - run: make codecov-upload
    resource_class: arm.large
  sync:
    executor: release
    working_directory: ~/nonnative
    steps:
      - checkout-submodules
      - run: make sync push
    resource_class: arm.large
  version:
    executor: release
    working_directory: ~/nonnative
    steps:
      - checkout-submodules
      - run: version
      - run: package
    resource_class: arm.large
  wait-all:
    executor: alpine
    resource_class: small
    steps:
      - run: echo "all applicable jobs finished"

workflows:
  nonnative:
    jobs:
      - build
      - sync:
          requires:
            - build
          filters:
            branches:
              ignore: master
      - version:
          context: gh
          serial-group: << pipeline.project.slug >>/version
          requires:
            - build
          filters:
            branches:
              only: master
      - wait-all:
          requires:
            - build
            - sync
            - version
