version: 1.0
processes:
  -
    name: go
    go:
      tools: [prof, trace, cover]
      output: reports
      executable: thisshouldbelong
      command: server
      parameters:
        - --level=info
    timeout: 5
    port: 8000
    log: reports/go.log
