version: "1.0"
name: test
url: http://localhost:4567
log: test/reports/nonnative.log
processes:
  - name: go
    go:
      tools: [prof, trace, cover]
      output: reports
      executable: thisshouldbelong
      command: server
      parameters:
        - --level=info
    timeout: 5
    port: 8000
    log: test/reports/go.log
