version: 1.0
processes:
  -
    name: start_1
    command: features/support/bin/start 12_321
    timeout: 5
    wait: 0.2
    host: 127.0.0.1
    port: 12321
    log: reports/12_321.log
    signal: INT
    environment:
      STRING: true
  -
    name: start_2
    command: features/support/bin/start 12_322
    timeout: 5
    wait: 0.2
    port: 12322
    log: reports/12_322.log
    signal: TERM
