version: "1.0"
name: test
url: http://localhost:4567
log: test/reports/nonnative.log
processes:
  - name: start_1
    command: features/support/bin/start 12_321
    timeout: 5
    wait: 0.2
    host: 127.0.0.1
    port: 12321
    log: test/reports/12_321.log
    signal: INT
    environment:
      STRING: true
  - name: start_2
    command: features/support/bin/start 12_322
    timeout: 5
    wait: 0.2
    port: 12322
    log: test/reports/12_322.log
    signal: TERM
