version: 1.0
strategy: manual
servers:
  -
    name: tcp_server_1
    class: Nonnative::Features::TCPServer
    timeout: 1
    port: 12323
    log: features/logs/tcp_server_1.log
    proxy:
      type: fault_injection
      port: 20000
      log: features/logs/proxy_tcp_server_1.log
  -
    name: tcp_server_2
    class: Nonnative::Features::TCPServer
    timeout: 1
    port: 12324
    log: features/logs/tcp_server_2.log
    proxy:
      type: fault_injection
      port: 20001
      log: features/logs/proxy_tcp_server_2.log
