version: 2.0
servers:
  -
    name: tcp_server_1
    class: Nonnative::Features::TCPServer
    timeout: 1
    host: 127.0.0.1
    port: 12323
    log: reports/tcp_server_1.log
  -
    name: tcp_server_2
    class: Nonnative::Features::TCPServer
    timeout: 1
    port: 12324
    log: reports/tcp_server_2.log
