version: "1.0"
name: test
url: http://localhost:4567
log: test/reports/nonnative.log
services:
  - name: service_1
    host: 127.0.0.1
    port: 20006
    proxy:
      kind: fault_injection
      host: 127.0.0.1
      port: 30000
      log: test/reports/proxy_service_1.log
      wait: 1
